"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { FileText, Download, PenTool, AlertTriangle, Users } from "lucide-react"
import { useAuth } from "@/lib/auth"
import { supabase } from "@/lib/supabase"

interface Lease {
  id: string
  landlord_id: string
  property_id: string
  start_date: string
  end_date: string
  monthly_rent: number
  deposit_amount: number
  status: string
  is_active: boolean
  signed_by_landlord: boolean
  signed_by_tenant: boolean
  cancellation_notice_date: string | null
  created_at: string
  landlord?: { first_name: string; last_name: string; email: string }
  property?: { title: string; address: string }
}

export default function TenantLeasesPage() {
  const { profile } = useAuth()
  const [leases, setLeases] = useState<Lease[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (profile?.id) fetchLeases()
  }, [profile?.id])

  const fetchLeases = async () => {
    try {
      const { data, error } = await supabase
        .from("leases")
        .select("*")
        .eq("tenant_id", profile?.id)
        .order("created_at", { ascending: false })

      if (error) throw error

      const enriched = await Promise.all(
        (data || []).map(async (lease) => {
          const [{ data: landlord }, { data: property }] = await Promise.all([
            supabase.from("profiles").select("first_name, last_name, email").eq("id", lease.landlord_id).maybeSingle(),
            supabase.from("properties").select("title, address").eq("id", lease.property_id).maybeSingle(),
          ])
          return { ...lease, landlord, property }
        })
      )
      setLeases(enriched)
    } catch (error) {
      console.error("Error fetching leases:", error)
    } finally {
      setLoading(false)
    }
  }

  const signLease = async (leaseId: string) => {
    try {
      const { error } = await supabase
        .from("leases")
        .update({ signed_by_tenant: true })
        .eq("id", leaseId)

      if (error) throw error

      const lease = leases.find(l => l.id === leaseId)
      if (lease?.signed_by_landlord) {
        await supabase.from("leases").update({ status: "active", is_active: true }).eq("id", leaseId)
        if (lease.property_id) {
          await supabase.from("properties").update({ status: "occupied" }).eq("id", lease.property_id)
        }
      }
      fetchLeases()
    } catch (error) {
      console.error("Error signing lease:", error)
    }
  }

  const generatePDF = (lease: Lease) => {
    const doc = `<!DOCTYPE html><html><head><title>Lease Agreement</title>
<style>body{font-family:Georgia,serif;max-width:800px;margin:0 auto;padding:40px;color:#1a1a1a;line-height:1.6}h1{text-align:center;color:#ea580c;border-bottom:2px solid #ea580c;padding-bottom:10px}h2{color:#333;margin-top:30px}.parties{background:#fff7ed;padding:20px;border-radius:8px;margin:20px 0}.signature{display:flex;justify-content:space-between;margin-top:60px}.sig-block{text-align:center;width:45%}.sig-line{border-top:1px solid #333;padding-top:8px;margin-top:60px}.terms{background:#f8fafc;padding:20px;border-radius:8px;border-left:4px solid #ea580c}.footer{text-align:center;margin-top:40px;color:#666;font-size:12px}</style></head><body>
<h1>RESIDENTIAL LEASE AGREEMENT</h1>
<p style="text-align:center;color:#666">Generated by MyYard</p>
<div class="parties"><h2>1. PARTIES</h2>
<p><strong>LANDLORD:</strong> ${lease.landlord?.first_name} ${lease.landlord?.last_name}</p>
<p><strong>TENANT:</strong> ${profile?.first_name} ${profile?.last_name}</p></div>
<h2>2. PREMISES</h2><p><strong>${lease.property?.title}</strong><br/>${lease.property?.address}</p>
<h2>3. TERM</h2><p>From <strong>${new Date(lease.start_date).toLocaleDateString("en-ZA")}</strong> to <strong>${new Date(lease.end_date).toLocaleDateString("en-ZA")}</strong></p>
<h2>4. RENTAL</h2><p>Monthly: <strong>R${lease.monthly_rent?.toLocaleString()}</strong> | Deposit: <strong>R${lease.deposit_amount?.toLocaleString()}</strong></p>
<h2>5. CANCELLATION</h2><div class="terms"><p>Either party may cancel with <strong>20 calendar days</strong> written notice.</p></div>
<h2>6. GENERAL TERMS</h2><ul><li>Maintain premises in good condition</li><li>No structural alterations without consent</li><li>Tenant responsible for utilities</li><li>Deposit refunded within 14 days of vacating</li><li>Governed by the Rental Housing Act (No. 50 of 1999)</li></ul>
<div class="signature"><div class="sig-block"><div class="sig-line"><strong>LANDLORD</strong><br/>${lease.landlord?.first_name} ${lease.landlord?.last_name}<br/>Date: ${lease.signed_by_landlord ? new Date().toLocaleDateString("en-ZA") : "________________"}</div></div>
<div class="sig-block"><div class="sig-line"><strong>TENANT</strong><br/>${profile?.first_name} ${profile?.last_name}<br/>Date: ${lease.signed_by_tenant ? new Date().toLocaleDateString("en-ZA") : "________________"}</div></div></div>
<div class="footer"><p>MyYard &copy; ${new Date().getFullYear()}</p></div></body></html>`

    const blob = new Blob([doc], { type: "text/html" })
    const url = URL.createObjectURL(blob)
    const pw = window.open(url, "_blank")
    if (pw) pw.onload = () => pw.print()
  }

  const getStatusBadge = (lease: Lease) => {
    if (lease.status === "cancellation_pending") return <Badge variant="destructive">Cancellation Pending</Badge>
    if (lease.status === "cancelled") return <Badge variant="secondary">Cancelled</Badge>
    if (lease.is_active) return <Badge className="bg-green-100 text-green-800">Active</Badge>
    if (lease.signed_by_landlord && lease.signed_by_tenant) return <Badge className="bg-blue-100 text-blue-800">Fully Signed</Badge>
    return <Badge variant="secondary">Pending Signatures</Badge>
  }

  if (loading) {
    return <div className="space-y-6">{[...Array(3)].map((_, i) => <Card key={i} className="animate-pulse"><CardHeader><div className="h-4 bg-gray-200 rounded w-3/4"></div></CardHeader></Card>)}</div>
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-gray-900" data-testid="tenant-leases-title">My Leases</h2>
        <p className="text-gray-600">View and manage your lease agreements</p>
      </div>

      {leases.length > 0 ? (
        <div className="space-y-4">
          {leases.map((lease) => (
            <Card key={lease.id} data-testid={`tenant-lease-${lease.id}`}>
              <CardContent className="p-6">
                <div className="flex items-start justify-between">
                  <div className="space-y-2">
                    <div className="flex items-center gap-3">
                      <FileText className="h-5 w-5 text-orange-500" />
                      <h3 className="font-semibold text-lg">{lease.property?.title}</h3>
                      {getStatusBadge(lease)}
                    </div>
                    <p className="text-sm text-gray-600">{lease.property?.address}</p>
                    <div className="flex items-center gap-4 text-sm text-gray-500">
                      <span className="flex items-center gap-1"><Users className="h-4 w-4" />Landlord: {lease.landlord?.first_name} {lease.landlord?.last_name}</span>
                      <span>R{lease.monthly_rent?.toLocaleString()}/mo</span>
                      <span>{new Date(lease.start_date).toLocaleDateString()} - {new Date(lease.end_date).toLocaleDateString()}</span>
                    </div>
                    <div className="flex items-center gap-2 mt-2">
                      <span className={`text-xs px-2 py-0.5 rounded ${lease.signed_by_landlord ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-500"}`}>
                        Landlord {lease.signed_by_landlord ? "Signed" : "Pending"}
                      </span>
                      <span className={`text-xs px-2 py-0.5 rounded ${lease.signed_by_tenant ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-500"}`}>
                        Tenant {lease.signed_by_tenant ? "Signed" : "Pending"}
                      </span>
                    </div>
                    {lease.cancellation_notice_date && (
                      <div className="flex items-center gap-1 text-sm text-red-600 mt-1">
                        <AlertTriangle className="h-4 w-4" />
                        Cancellation effective {new Date(lease.end_date).toLocaleDateString()}
                      </div>
                    )}
                  </div>
                  <div className="flex gap-2">
                    {!lease.signed_by_tenant && lease.status !== "cancelled" && (
                      <Button size="sm" onClick={() => signLease(lease.id)} data-testid={`tenant-sign-${lease.id}`}>
                        <PenTool className="h-4 w-4 mr-1" />Sign
                      </Button>
                    )}
                    <Button size="sm" variant="outline" onClick={() => generatePDF(lease)}>
                      <Download className="h-4 w-4 mr-1" />PDF
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <Card><CardContent className="text-center py-12">
          <FileText className="h-12 w-12 text-gray-400 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-gray-900 mb-2">No lease agreements</h3>
          <p className="text-gray-600">Your lease agreements will appear here when a landlord creates one for you</p>
        </CardContent></Card>
      )}
    </div>
  )
}
